version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Qwerty12
      POSTGRES_DB: ai_chat_subscription
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Qwerty12
      POSTGRES_DB: ai_chat_subscription_test
    ports:
      - '5434:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://admin:Qwerty12@postgres:5432/ai_chat_subscription
      - TEST_DATABASE_URL=postgres://admin:Qwerty12@postgres_test:5432/ai_chat_subscription_test
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      postgres_test:
        condition: service_healthy
    command: >
      sh -c "npx ts-node src/scripts/seed-data.ts && node dist/server.js"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app

volumes:
  postgres_data:
  postgres_test_data: