export enum ErrorType {
  VALIDATION = 'VALIDATION_ERROR',
  FORBIDDEN = 'FORBIDDEN_ERROR',
  DUPLICATION = 'DUPLICATION_ERROR',
  USAGE_LIMIT = 'USAGE_LIMIT_EXCEEDED',
  NOT_FOUND = 'NOT_FOUND_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED_ERROR',
  INTERNAL = 'INTERNAL_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
}
